### ISSUE TITLE
Build a Raw KinderNeutron Model

### ISSUE THREAD

**Issue by kinderasteroid** [kinderneutron/kinderneutron-DlModelLc#1]
@varshavshetty 
**Task:** To Build a Raw Tensorflow Model Which Can Detect Person Based On the Feedback From the Camera 

To-Do: Mentioned Me in the Comment And Inform when you finish the Task and change the Project status For Review and assign me

**Comment by kinderasteroid** [comment]
Hello @varshavshetty , Did you Run the Env Setup, If Yes Did it work good?

**Comment by varshavshetty** [comment]
> Hello @varshavshetty , Did you Run the Env Setup, If Yes Did it work good?

no i didn't run Env Setup
